name: mi-card-app
version: 0.0.1
summary: Super Cool App
description: Super Cool App that does everything!

confinement: strict
base: core18
grade: stable

slots:
  dbus-mi-card-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.mi_card_app # adjust accordingly to your app name and
    
apps:
  mi-card-app:
    command: mi_card_app
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-mi-card-app
parts:
  mi-card-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

